language: generic

jobs:
  include:
    - name: python-lint
      script: 
      - sudo apt-get install -y python3 python3-pip
      - sudo pip3 install pycodestyle
      - sudo pycodestyle sample_code/python
    - name: cpp-lint
      script:
      - sudo apt-get install -y python3 python3-pip
      - sudo pip3 install cpplint
      - sudo cpplint --recursive sample_code/cpp
