language: generic

jobs:
  include:
    - name: python-lint
      script: 
        apt-get install -y python3 python3-pip
        pip3 install pycodestyle && pycodestyle sample_code/python
    - name: cpp-lint
      script:
        apt-get install -y python3 python3-pip
        pip3 install cpplint && cpplint --recursive sample_code/cpp