language: generic

jobs:
  include:
    # Pep8 linter for python code
    - name: python-lint
      script: 
      - sudo apt-get install -y python3 python3-pip
      - sudo pip3 install pycodestyle
      - sudo pycodestyle sample_code/python

    # Google style guide linter for C++ code
    - name: cpp-lint
      script:
      - sudo apt-get install -y python3 python3-pip
      - sudo pip3 install cpplint
      - sudo cpplint --recursive sample_code/cpp

# TODO
# - doxygen build on push to master/develop