language: generic

jobs:
  include:
    # Pep8 linter for python code
    - name: python-lint
      script: 
      - sudo apt-get install -y python3 python3-pip
      - sudo pip3 install pycodestyle
      - sudo pycodestyle sample_code/python

    # Google style guide linter for C++ code
    - name: cpp-lint
      script:
      - sudo apt-get install -y python3 python3-pip
      - sudo pip3 install cpplint
      - sudo cpplint --recursive sample_code/cpp

    # Doxygen coverage measure for included files
    # - name: doxygen-coverage 
    #   script:
    #   - sudo apt-get install -y python3 python3-pip doxygen
    #   - sudo pip3 install coverxygen
    #   - sudo sed -i '' 's/GENERATE_XML           = NO/GENERATE_XML           = YES/g' docs/Doxyfile
    #   - cd docs && sudo doxygen Doxyfile && cd ..
    #   - python3 -m coverxygen --xml-dir ./docs/xml --src-dir ./sample_code/python --output doc-coverage.info

# TODO
# - doxygen build on push to master/develop